### ISSUE TITLE
Linux compatibility with atomics

### ISSUE THREAD

**Issue by cascade256** [f1nalspace/final_game_tech#2]
First off, I want to say that this project is great! I saw it on Handmade Network and it seems like a much lighter weight option than QT and has plans for more features than GLFW.  I am looking forward to using it!

I have been working on getting everything working on Linux on my fork here: https://github.com/cascade256/final_game_tech 
but I am running into an issue porting the atomics. After looking into it, I was unable to find the equivalent macros for GCC. It seems like the C++11 std::atomics library is the recommended replacement. I noticed that the MSVC macros are also deprecated in favor of std::atomics.  

Do you think std::atomics is the best option for a cross platform final_platform_layer?

Thanks for all your work on this!

**Comment by f1nalspace** [comment]
Thanks, glad you like it! Nice fork so far - its pretty much how i would approached it.
Regarding your question: I still havent looked into linux support yet, so i am not sure. Using std::atomics is a option, but i rather would use a intrinsic directly - just because i have no idea what happens in the background of std atomics. But from my past use of atomics, it was heavely based on templates. So you basically have std::atomic<int64_t> and use a fetch, read, write function. This works but has the downside of all your types must be std::atomic<> and i dont want that.

**Comment by f1nalspace** [comment]
*Edit:
Found something -> http://gcc.gnu.org/onlinedocs/gcc-4.4.3/gcc/Atomic-Builtins.html#Atomic-Builtins
This looks exactly how i want it to integrate it. In worst case, x86 assembly directly...

**Comment by cascade256** [comment]
Those look great, and it looks like they even work with clang. https://llvm.org/docs/Atomics.html

 I will see if I can get that working, thanks for the help!
